### ISSUE TITLE
1.3.0 broken and 2.0 not available on npm

### ISSUE THREAD

**Issue by jaredmoody** [danielbayley/jest-preset-coffeescript#46]
1. Please yank 1.3.0 since it overwrites package.json - my CI started failing because of this today
2. The README now contains instructions that don't work. Perhaps 2.0 needs to be published, but either way it might be a good idea to either move 2.0 instructions to a branch until it's published or make a note that the instructions are for an unreleased version

**Comment by unscene** [comment]
Was able to install it at least by setting up an .npmrc file:

```
//npm.pkg.github.com/:_authToken=<your personal access token>
@danielbayley:registry=https://npm.pkg.github.com
```

And then installing with:

```
npm install @danielbayley/jest-preset-coffeescript
```

But I am still unable to get it to work when I add the "jest" piece to the package.json

**Comment by danielbayley** [comment]
@jaredmoody @unscene Sorry, things have been a bit chaotic recently…

I wanted to release a quick update in response to #35. Initially it seemed like a simple version bump to Jest, but it turned out they altered an upstream config option which broke this package, and forced me to quickly rewrite how it works (See https://github.com/facebook/jest/pull/9495#issuecomment-607566969).

Since the CI was passing, I pushed those changes, which was a mistake. Also, I didn't realise GitHub Packages were now immutable, as the last time I tested them was during the beta period, before this was the case.

Anyway, I'll fix this ASAP and post an update, including to `npm`… Although I want to migrate solely to GitHub Packages in future.

**Comment by fcostarodrigo** [comment]
```bash
● Validation Error:

  Module /Users/Dan/Work/dev/npm/jest-preset-coffeescript in the setupFilesAfterEnv option was not found.
         <rootDir> is: /Users/roc58/myCode/pug-cli

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pug-cli@1.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pug-cli@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/roc58/.npm/_logs/2020-07-05T23_58_40_125Z-debug.log
The terminal process terminated with exit code: 1
```

I have this error when using the version in the github packages, but this error does not happen when installing directly from GitHub `npm i https://github.com/danielbayley/jest-preset-coffeescript`.

**Comment by edemaine** [comment]
My CI also started failing and tracked it down to this. After many failed attempts to use the Github package (very hard to use with `yarn`, it seems), I tried `yarn add https://github.com/danielbayley/jest-preset-coffeescript` and then running `jest`. Unfortunately, this still causes the problem of clobbering `package.json` (#45). Is the fixed version not on Github? I don't see any commits that would fix it.

**Comment by danielbayley** [comment]
@edemaine This has been resolved here https://github.com/danielbayley/jest-preset-coffeescript/commit/07038d633a3e88d4c63e8608439f35741f6e97d7.

**Comment by danielbayley** [comment]
> The README now contains instructions that don't work.

@jaredmoody @weotch @unscene @jacekk @Nevon @fcostarodrigo They clearly assume you already have `npm` configured to work with GitHub Packages:

> Assuming you already have npm [configured](https://help.github.com/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages#authenticating-to-github-package-registry) to work with GitHub Packages:

apart from the steps specific to this package:

> `npm config set @danielbayley:registry https://npm.pkg.github.com`

But I have [clarified a few things in the `README`](https://github.com/danielbayley/jest-preset-coffeescript/commit/ef8061fe3a41ae8f6deb9ecd3d2ffafd3fc83951) just now, along with a couple of other fixes… please see latest [release](https://github.com/danielbayley/jest-preset-coffeescript/releases). Sorry for the delay! Everything should be working now, but please test… thanks! 👍

**Comment by edemaine** [comment]
It seems that the new version still isn't on NPM: https://www.npmjs.com/package/jest-preset-coffeescript doesn't list it (perhaps because of the deprecation notice?) and `npm install jest-preset-coffeescript@2` doesn't work.

Also, version `1.3.0` has not been pulled from NPM; I just got my `package.json` clobbered when running `npm install` (depending on version `^1.1.1` which auto-upgraded).

**Comment by fcostarodrigo** [comment]
I am using my own solution now. Just published in case it is useful for someone else as well.
https://www.npmjs.com/package/coffeescript-jest-preset

About the package not being on npm, the author is publishing the package on github, so you have to configure npm to get the package from github.
